include:
  - project: 'strowi/ci-templates'
    file: '/build.yml'
  - project: 'strowi/ci-templates'
    file: '/tests.yml'
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  CODE_QUALITY_DISABLED: "true"
  PLATFORMS: linux/amd64,linux/arm64

stages:
  - build
  - test
  - release

build:
  extends: .build
  stage: build
  script:
    - build_image

dgoss:
  extends: .dgoss
  script:
    - dgoss_run -t --entrypoint sh $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}

container_scanning:
  extends: .container_scanning

release_branch:
  extends: .build
  stage: release
  script:
    - docker pull "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"
    - docker tag "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}" "strowi/ansible:${CI_COMMIT_REF_SLUG}"
    - echo $DOCKER_TOKEN | docker login -u strowi --password-stdin
    - docker push "strowi/ansible:${CI_COMMIT_REF_SLUG}"
  rules:
    - if: '$CI_COMMIT_BRANCH'
      when: always
    - when: never

release:
  extends: .build
  stage: release
  script:
    - release_latest
    - test -n ${CI_COMMIT_TAG} && release_tag
    - docker tag "$CI_REGISTRY_IMAGE" "strowi/$CI_PROJECT_NAME"
    - echo $DOCKER_TOKEN | docker login -u strowi --password-stdin
    - docker push "strowi/$CI_PROJECT_NAME"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    - when: never
