#!/bin/sh
#
# Simple wrapper for executing ansible-galaxy and ansible-playbook
# with local connection.
#
# USAGE:
#    ansible-playbook-wrapper  [other ansible-playbook arguments]
#
# ENVIRONMENT VARIABLES:
#
#    - REQUIREMENTS: requirements filename; default = "requirements.yml"
#    - PLAYBOOK:     playbook filename;     default = "playbook.yml"
#    - INVENTORY:    inventory filename;    default = "/etc/ansible/hosts"
#


#
# install Galaxy roles, if any
#

if [ -z "$REQUIREMENTS" ]; then
    REQUIREMENTS=requirements.yml
fi

if [ -f "$REQUIREMENTS" ]; then
    apk --update add git
    ansible-galaxy install -r $REQUIREMENTS
fi


#
# execute playbook
#

if [ -n "$CI_GPG_PRIVATE_KEY" ]; then
  echo -ne " Import GPG-Key... "
  echo "$CI_GPG_PRIVATE_KEY"|base64 -d | gpg --import \
  && echo "successful."
  git crypt unlock
fi

if [ -z "$PLAYBOOK" ]; then
    PLAYBOOK=playbook.yml
fi


if [ -z "$INVENTORY" ]; then
    exec ansible-playbook        \
       $PLAYBOOK                 \
       --connection=local        \
       "$@"
else
    exec ansible-playbook        \
       -i $INVENTORY  $PLAYBOOK  \
       --connection=local        \
       "$@"
fi
